subscription {
  gameState {
    ... on SymbolPlacement {
      x
      y
      symbol
    }
    ... on GameWin {
      player {
        user {
          username
        }
      }
    }
    ... on GameSurrender {
      player {
        user {
          username
        }
      }
    }
  }
}
